apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: blue
    slot: blue
  name: blue
spec:
  containers:
  - image: httpd:2.4.35
    name: blue
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo 'Hello blue' > /usr/local/apache2/htdocs/index.html"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
