apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: green
    slot: green
  name: green
spec:
  containers:
  - image: httpd:2.4.46
    name: green
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo 'Hello green' > /usr/local/apache2/htdocs/index.html"]
    resources: {}    
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
