apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}-staging
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "website.selectorLabels" . | nindent 4 }}
    {{- if eq .Values.productionSlot "blue" }}
    slot: green
    {{- else }}
    slot: blue
    {{- end }}